### ISSUE TITLE
Rename pages to use page suffix

### ISSUE THREAD

**Issue by boriskozak** [allcleardev/allclear-app#308]
All top-level components should utilize the page suffix and be placed in the pages/ directory.   
  
  
As part of this effort, you will need to update all import routes accordingly. You will also need to rename the files using the .page suffix.

Taking these routes for example:  
 ![](https://ilico.aha.io/attachments/6814281228202282228/token/fcc85ba07b7d7b44e9b706e77c075ab87463d4fef0edc72f9db12209c8d3d5df.download?size=original)  
  
  
component would be called:SignUpPage | file would be called: sign-up.page.js  
component would be called:SignUpVerificationPage | file would be called: sign-up-verification.page.js  
component would be called:VerifyingPage | file would be called: verifying.page.js  
component would be called:AuthPage | file would be called: auth.page.js

<span data-href="#aha_attachments_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

<span data-href="#aha_attachment_6814281228202282228" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>image.png (https://ilico.aha.io/attachments/6814281228202282228/token/fcc85ba07b7d7b44e9b706e77c075ab87463d4fef0edc72f9db12209c8d3d5df.download?size=original)
<span data-href="#aha_attachments_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://ilico.aha.io/features/ALLCLEAR-166

**Comment by crimsonsunset** [comment]
this is done
